// TARS Dashboard - E-Ink Optimized
// Password: harsha_tars

const CONFIG = {
    password: 'harsha_tars',
    refreshInterval: 5 * 60 * 1000, // 5 minutes
    apiEndpoint: '/api/status.json', // Will be generated by backend
};

// State
let isAuthenticated = false;
let refreshTimer = null;

// Initialize
document.addEventListener('DOMContentLoaded', () => {
    checkAuth();
    setupEventListeners();
});

// Check authentication
function checkAuth() {
    const saved = sessionStorage.getItem('tars_auth');
    if (saved === 'true') {
        isAuthenticated = true;
        showDashboard();
        loadData();
        startAutoRefresh();
    } else {
        showPasswordPrompt();
    }
}

// Show password prompt
function showPasswordPrompt() {
    const overlay = document.createElement('div');
    overlay.className = 'password-overlay';
    overlay.innerHTML = `
        <h2>🔒 TARS Command Center</h2>
        <p>Enter password to access</p>
        <input type="password" class="password-input" id="password-input" placeholder="Password">
        <button class="btn" onclick="verifyPassword()">UNLOCK</button>
        <div class="error-msg" id="error-msg"></div>
    `;
    document.body.appendChild(overlay);
    
    // Enter key support
    document.getElementById('password-input').addEventListener('keypress', (e) => {
        if (e.key === 'Enter') verifyPassword();
    });
    document.getElementById('password-input').focus();
}

// Verify password
function verifyPassword() {
    const input = document.getElementById('password-input').value;
    if (input === CONFIG.password) {
        isAuthenticated = true;
        sessionStorage.setItem('tars_auth', 'true');
        document.querySelector('.password-overlay').remove();
        showDashboard();
        loadData();
        startAutoRefresh();
    } else {
        document.getElementById('error-msg').textContent = '❌ Incorrect password';
        document.getElementById('password-input').value = '';
    }
}

// Show dashboard
function showDashboard() {
    document.querySelector('.container').style.display = 'block';
}

// Setup event listeners
function setupEventListeners() {
    document.getElementById('refresh-btn').addEventListener('click', () => {
        loadData();
    });
}

// Load data from API
async function loadData() {
    try {
        updateLastRefreshTime();
        
        // For now, use mock data
        // In production, this would fetch from the API
        const data = await fetchData();
        
        updateStats(data);
        updateSystemStatus(data);
        updateActivity(data);
        
    } catch (error) {
        console.error('Failed to load data:', error);
        showError('Failed to load data');
    }
}

// Fetch data (mock for now, will be real API)
async function fetchData() {
    // Mock data - replace with actual API call
    return {
        memories: 103,
        tasks: 5,
        emailsIn: 2,
        emailsOut: 1,
        systemStatus: {
            memoryDb: 'online',
            coolifyApi: 'online',
            telegramBot: 'online',
            githubSsh: 'online'
        },
        recentActivity: [
            { time: '17:05', action: 'Created coolify-deploy skill' },
            { time: '16:59', action: 'Deployed brutalist landing page' },
            { time: '16:35', action: 'Updated subdomain registry' },
            { time: '16:30', action: 'Connected Coolify API' },
            { time: '15:45', action: 'Generated SSH key for GitHub' }
        ]
    };
    
    // Real API call (when backend is ready):
    // const response = await fetch(CONFIG.apiEndpoint);
    // return await response.json();
}

// Update stats
function updateStats(data) {
    document.getElementById('memories').textContent = data.memories;
    document.getElementById('tasks').textContent = data.tasks;
    document.getElementById('emails-in').textContent = data.emailsIn;
    document.getElementById('emails-out').textContent = data.emailsOut;
}

// Update system status
function updateSystemStatus(data) {
    const container = document.getElementById('system-status');
    const statuses = [
        { name: 'Memory DB', status: data.systemStatus.memoryDb },
        { name: 'Coolify API', status: data.systemStatus.coolifyApi },
        { name: 'Telegram Bot', status: data.systemStatus.telegramBot },
        { name: 'GitHub SSH', status: data.systemStatus.githubSsh }
    ];
    
    container.innerHTML = statuses.map(s => `
        <div class="status-item">
            <span class="dot ${s.status}"></span> ${s.name}
        </div>
    `).join('');
}

// Update activity
function updateActivity(data) {
    const container = document.getElementById('activity');
    container.innerHTML = data.recentActivity.map(a => `
        <div class="activity-item">
            <strong>${a.time}</strong> - ${a.action}
        </div>
    `).join('');
}

// Update last refresh time
function updateLastRefreshTime() {
    const now = new Date();
    const timeStr = now.toLocaleTimeString('en-US', { 
        hour: '2-digit', 
        minute: '2-digit',
        hour12: false 
    });
    document.getElementById('last-update').textContent = `Last: ${timeStr}`;
}

// Show error
function showError(msg) {
    // Simple error display
    console.error(msg);
}

// Start auto-refresh
function startAutoRefresh() {
    if (refreshTimer) clearInterval(refreshTimer);
    refreshTimer = setInterval(() => {
        loadData();
    }, CONFIG.refreshInterval);
}

// Stop auto-refresh (for cleanup)
function stopAutoRefresh() {
    if (refreshTimer) {
        clearInterval(refreshTimer);
        refreshTimer = null;
    }
}

// Handle visibility change (pause/resume auto-refresh)
document.addEventListener('visibilitychange', () => {
    if (document.hidden) {
        stopAutoRefresh();
    } else {
        startAutoRefresh();
        loadData();
    }
});
